apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  redis.host: redis-service
  redis.port: '6379'
  spring.datasource.url: jdbc:mysql://db:3306/recipe-book?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
  mysql.database: recipe-book
  resource.host: resource
  resource.port: '8080'
  