apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource
spec:
  replicas: 1
  selector:
    matchLabels:
      component: resource
  template:
    metadata:
      labels:
        component: resource
    spec:
      containers:
        - name: resource
          image: pozzallo/resource
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: redis.host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: redis.port
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: spring.datasource.url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: mysql.user
            - name: SPRING_DATASOURCE_PASSWORD
              value: varia123